trigger: none   # Run manually for Dev infra

pool:
  name: Default   # Your self-hosted agent pool name

variables:
- group: terraform-secrets   # Linked to your Key Vault (Azuredevopskv12)

stages:
- stage: Dev
  displayName: "Deploy Dev Infrastructure"
  jobs:
  - job: Terraform_Dev
    displayName: "Terraform Apply for Dev"
    steps:
    # ✅ Checkout repo so terraform_project/terraform exists
    - checkout: self

    # ✅ Install Terraform manually (since Marketplace extension not installed)
    - script: |
        curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_windows_amd64.zip
        tar -xf terraform.zip
        move terraform.exe C:\Windows\System32\
        terraform -version
      displayName: "Install Terraform"

    # ✅ Terraform Init with backend
    - script: |
        terraform init `
          -backend-config="resource_group_name=rg-terraform-state" `
          -backend-config="storage_account_name=tfstatestorage12321" `
          -backend-config="container_name=tfstate" `
          -backend-config="key=dev.terraform.tfstate" `
          -backend-config="access_key=$(ARM-STORAGE-KEY)"
      workingDirectory: terraform_project/terraform
      env:
        ARM_CLIENT_ID: $(ARM-CLIENT-ID)
        ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
        ARM_TENANT_ID: $(ARM-TENANT-ID)

    # ✅ Terraform Plan
    - script: terraform plan -var-file="env/dev.tfvars" -out=tfplan
      workingDirectory: terraform_project/terraform
      env:
        ARM_CLIENT_ID: $(ARM-CLIENT-ID)
        ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
        ARM_TENANT_ID: $(ARM-TENANT-ID)

    # ✅ Terraform Apply
    - script: terraform apply -auto-approve tfplan
      workingDirectory: terraform_project/terraform
      env:
        ARM_CLIENT_ID: $(ARM-CLIENT-ID)
        ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
        ARM_TENANT_ID: $(ARM-TENANT-ID)
