trigger: none   # Run manually for Dev infra

pool:
  name: Default   # self-hosted Windows agent

variables:
- group: terraform-secrets   # Linked to your Key Vault (Azuredevopskv12)

stages:
- stage: Dev
  displayName: "Deploy Dev Infrastructure"
  jobs:
  - deployment: Apply_Dev
    displayName: "Terraform Apply (Dev)"
    environment: Dev-Deploy   # <-- Add approvals in DevOps UI if needed
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          # Terraform Init
          - script: terraform init -backend-config="resource_group_name=rg-terraform-state" -backend-config="storage_account_name=tfstatestorage12321" -backend-config="container_name=tfstate" -backend-config="key=dev.terraform.tfstate" -backend-config="access_key=$(ARM-STORAGE-KEY)"
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Terraform Init (Dev)"
            env:
              ARM_CLIENT_ID: $(ARM-CLIENT-ID)
              ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
              ARM_TENANT_ID: $(ARM-TENANT-ID)

          # Terraform Plan
          - script: terraform plan -var-file="env/dev.tfvars" -out=tfplan
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Terraform Plan (Dev)"
            env:
              ARM_CLIENT_ID: $(ARM-CLIENT-ID)
              ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
              ARM_TENANT_ID: $(ARM-TENANT-ID)

          # Terraform Apply
          - script: terraform apply -auto-approve tfplan
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Terraform Apply (Dev)"
            env:
              ARM_CLIENT_ID: $(ARM-CLIENT-ID)
              ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
              ARM_TENANT_ID: $(ARM-TENANT-ID)
