trigger: none   # Run manually

pool:
  name: Default

variables:
- group: terraform-secrets

stages:
- stage: DestroyProd
  displayName: "Destroy Prod Infrastructure"
  jobs:
  - deployment: Destroy_Prod
    displayName: "Terraform Destroy (Prod)"
    environment: Prod-Destroy   # <-- Approval required
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          # Terraform Init
          - script: terraform init -backend-config="resource_group_name=rg-terraform-state" -backend-config="storage_account_name=tfstatestorage12321" -backend-config="container_name=tfstate" -backend-config="key=prod.terraform.tfstate" -backend-config="access_key=$(ARM-STORAGE-KEY)"
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Terraform Init (Prod)"
            env:
              ARM_CLIENT_ID: $(ARM-CLIENT-ID)
              ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
              ARM_TENANT_ID: $(ARM-TENANT-ID)

          # Terraform Destroy
          - script: terraform destroy -auto-approve -var-file="env/prod.tfvars"
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Terraform Destroy (Prod)"
            env:
              ARM_CLIENT_ID: $(ARM-CLIENT-ID)
              ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
              ARM_TENANT_ID: $(ARM-TENANT-ID)
